[workspace]

members = [
  "hcobs",
  "owning_iovec",
  "sliding_deque",
  "vouched_time",
]

resolver = "2"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
