[workspace]

members = [
  "hcobs",
  "owning_iovec",
  "sliding_deque",
  "trivial_zip_wrapper",
  "vouched_time",
  "woodpile",
]

resolver = "2"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
